### PR TITLE
Fix return types

### LINKED ISSUE #1361: Latest phpstan is reporting missing return statements
phpstan is reporting various functions that have return types documented but do not always return the documented type.

This is causing CI to fail.

### PR DESCRIPTION
**Pull request by phil-davis**
Fixes #1361 

I have tried to minimize changes to real code, and o mostly just delete or adjust PHPdoc to match reality. That gets CI green with the minimum impact.

### CODE REVIEW

**Comment by phil-davis** [comment]
```
------ -------------------------------------------------------- 
  Line   tests/Sabre/CalDAV/ExpandEventsDTSTARTandDTENDTest.php  
 ------ -------------------------------------------------------- 
  100    Variable $vObject might not be defined.                 
 ------ -------------------------------------------------------- 
```

phpstan fails in CI, but I don't get this fail locally.

**Review by ChristophWurst — APPROVED** [review]

File: lib/CalDAV/Plugin.php [hunk 1]
```diff
@@ -264,6 +264,8 @@ public function report($reportName, $report, $path)
 
                 return false;
         }
+
+        return true;
```
Comment (phil-davis) [inline lib/CalDAV/Plugin.php:268]: what to do about these sort of things?
I guess that this code is never supposed to get past the switch cases. But what if it does? return true or false?

File: lib/CalDAV/Schedule/Plugin.php [hunk 2]
```diff
@@ -735,9 +735,7 @@ public function outboxRequest(IOutbox $outboxNode, RequestInterface $request, Re
 
     /**
      * This method is responsible for parsing a free-busy query request and
-     * returning it's result.
-     *
-     * @return string
```
Comment (phil-davis) [inline lib/CalDAV/Schedule/Plugin.php:740]: This function has no return statements at all. Why is the PHPdoc saying that it should return a string?

File: lib/CalDAV/Subscriptions/Subscription.php [hunk 3]
```diff
@@ -75,13 +75,15 @@ public function getName()
     /**
      * Returns the last modification time.
      *
-     * @return int
+     * @return int|false
```
Comment (staabm) [inline lib/CalDAV/Subscriptions/Subscription.php:78]: Before this change the method returned nothing, which means null.

File: lib/CalDAV/Plugin.php (hunk 1 above)
Comment (staabm) [reply lib/CalDAV/Plugin.php:268]: Maybe throw a exception?

File: lib/CalDAV/Subscriptions/Subscription.php (hunk 3 above)
Comment (phil-davis) [inline lib/CalDAV/Subscriptions/Subscription.php:78]: Callers seem to expect this return a falsy value if `lastmodified` is not set.

Comment (phil-davis) [reply lib/CalDAV/Subscriptions/Subscription.php:78]: I will replace false with null and revert the addition of `return false;` - that will be super-safe to do.

File: tests/Sabre/CalDAV/Backend/AbstractTest.php [hunk 4]
```diff
@@ -140,6 +140,8 @@ public function getCalendarObjects($calendarId)
                     ],
                 ];
         }
+
+        return [];
```
Comment (phil-davis) [inline tests/Sabre/CalDAV/Backend/AbstractTest.php:144]: From here, the changes are test code. 
We can put this sort of `return` at the end of a function to keep phpstan happy. It will never be executed, but that is no problem.

File: lib/CalDAV/Plugin.php (hunk 1 above)
Comment (phil-davis) [reply lib/CalDAV/Plugin.php:268]: I don't really know the calling path of all these plugins. If `$reportName` does not match any of the switch cases, then maybe the function is supposed to return "nothing" and not explode?

Is the existing omission of a return at the end of the function a bug or a feature?

Comment (phil-davis) [reply lib/CalDAV/Plugin.php]: I got rid of this and updated the PHPdoc to allow null.
