### PR TITLE
CalDAV/PropFilter: set empty array as default value for time-range

### LINKED ISSUE #1299: Incorrect default value for time-range CalDAV PropFilter
Currently, the default value for `time-range` in a CalDAV request is set to `false` here: https://github.com/sabre-io/dav/blob/master/lib/CalDAV/Xml/Filter/PropFilter.php

This does not seem to comply with https://tools.ietf.org/html/rfc4791#section-9.9, but it should rather be an empty array.

### PR DESCRIPTION
**Pull request by simonspa**
This changes the default value of `time-range` in CalDAV prop filters from `false` (not matching RFC 4791 https://tools.ietf.org/html/rfc4791#section-9.9) to an empty array.

This closes #1299.

### CODE REVIEW

**Comment by dilyanpalauzov** [comment]
See also https://github.com/sabre-io/dav/pull/1275.

**Comment by phil-davis** [comment]
I rebased and fixed the tests.

**Comment by phil-davis** [comment]
@DeepDiver1975 @staabm opinion please on this PR  and PR #1364

File: lib/CalDAV/Xml/Filter/PropFilter.php [hunk 1]
```diff
@@ -53,7 +53,7 @@ public static function xmlDeserialize(Reader $reader)
             'is-not-defined' => false,
             'param-filters' => [],
             'text-match' => null,
-            'time-range' => false,
+            'time-range' => [],
         ];
```
Comment (staabm) [inline lib/CalDAV/Xml/Filter/PropFilter.php:57]: I dont have expertise in the part of the codebase - but I think it might be usefull if we could declare constants for this `false`, `null` and `[]` magic values.

Comment (simonspa) [reply lib/CalDAV/Xml/Filter/PropFilter.php:57]: Might be a good idea, but goes a bit beyond this PR. I am not familiar at all with the SabreDAV code base and I am not willing to stir in it too much by adding constants. :wink:

Comment (phil-davis) [reply lib/CalDAV/Xml/Filter/PropFilter.php:57]: I can do refactoring for "magic values" after we sort out this PR.

@DeepDiver1975 or @evert are you familiar with this and can give an opinion on changing from `false` to `[]` ?

**Comment by phil-davis** [comment]
> See also #1275.

And #1319

**Comment by phil-davis** [comment]
@DeepDiver1975 any chance to look at this and #1364 please?

**Comment by simonspa** [comment]
Any chance this could get merged? I think it is ready and has been reviewed, the only open suggestion is some larger refactoring that should happen outside the scope of this PR.

**Comment by DeepDiver1975** [comment]
looks good to me :+1:  -> merge
