### PR TITLE
Fix PDO::PARAM_LOB binding for BYTEA columns in CalDAV and CardDAV

### LINKED ISSUE #1587: PostgreSQL error caused by comma
Sabre/DAV 4.7.0
PostgreSQL 15

Whenever a calendar or contact field contains a comma `,` it will fail to save.

FYI, a comma is escaped as `\,`. The backslash escaped as `\\` does not cause any problem.

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>4.7.0</s:sabredav-version>
  <s:exception>PDOException</s:exception>
  <s:message>SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bytea
CONTEXT:  unnamed portal parameter $3 = '...'</s:message>
</d:error>
```

### PR DESCRIPTION
**Pull request by sylvinus**
Fixes #1587 and #917

## Problem

On PostgreSQL, inserting iCalendar or vCard data containing backslash escape sequences (e.g. `\,` or `\n`, which are standard RFC 5545 TEXT escapes) into the `calendardata` or `carddata` BYTEA columns fails with:

      SQLSTATE[22P02]: Invalid text representation: 7 ERROR:
      invalid input syntax for type bytea

This happens because PDO binds parameters as `PARAM_STR` by default. For BYTEA columns, PostgreSQL's text input parser then interprets backslash sequences as invalid octal escapes.

## Fix

Bind `calendardata`/`carddata` parameters with `PDO::PARAM_LOB` in all write methods, consistent with the existing fix in `Sabre\DAV\PropertyStorage\Backend\PDO::propPatch()`. Also switch to named parameters with `bindParam()` and explicit types for all parameters, matching the PropertyStorage style.

Read methods now handle the `is_resource()` case since PDO may return BYTEA data as a PHP stream.

## Test

Added `testCreateCalendarObjectWithIcsEscapes` in `AbstractPDOTestCase` — inserts ICS data with `\,` and `\n` escapes, verifies round-trip integrity. Passes on PostgreSQL with the fix, fails without it.

I can also confirm this fixes our own codebase where we had large ICS import break 10% of the time because of such characters in events.

### CODE REVIEW

File: lib/CalDAV/Backend/PDO.php [hunk 1]
```diff
@@ -466,7 +466,7 @@ public function getCalendarObject($calendarId, $objectUri)
             'lastmodified' => (int) $row['lastmodified'],
             'etag' => '"'.$row['etag'].'"',
             'size' => (int) $row['size'],
-            'calendardata' => $row['calendardata'],
+            'calendardata' => is_resource($row['calendardata']) ? stream_get_contents($row['calendardata']) : $row['calendardata'],
```
Comment (alecpl) [inline lib/CalDAV/Backend/PDO.php]: The fact that you use LOB on INSERT does not mean that it will become a resource in SELECT. Imo, this part of the PR does not make sense. Or do I miss something?

**Review by provokateurin — APPROVED** [review]
